[package]
name = "presenced-popup"
version = "0.6.0"
description = "presenced-popup — Niri Wayland Discord Sync Companion"
edition = "2021"

[lib]
name = "presenced_popup_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
